test/testfailures.cpp(101): check equal (1, 0) failed
	1,  vs 0, 
suiteAssertEqual::ShouldFailByNoEqual: FAIL
test/testfailures.cpp(160): expected exception runtime_error not throw
suiteAssertException::ShouldFailByNoThrow: FAIL
test/testfailures.cpp(153): expected exception int not throw
suiteAssertException::ShouldFailByType: FAIL
test/testfailures.cpp(142): expected exception overflow_error("message") not throw
suiteAssertExceptionWithMessage::ShouldFailByChildException: FAIL
test/testfailures.cpp(128): expected exception runtime_error("hello") not throw
suiteAssertExceptionWithMessage::ShouldFailByNoThrow: FAIL
test/testfailures.cpp(135): check exception exception("message") failed
	catched exception: "another message"
suiteAssertExceptionWithMessage::ShouldFailByNotEqualMessage: FAIL
test/testfailures.cpp(121): expected exception int is not child of std::exception
suiteAssertExceptionWithMessage::ShouldFailByType: FAIL
test/testfailures.cpp(110): check not equal (1, 1) failed
	1,  vs 1, 
suiteAssertNe::ShouldFailByEqual: FAIL
unexpected test termination
test/testfailures.cpp(56): last checkpoint: UP_ASSERT_EQUAL
suiteCheckpoints::AssertEqualIsCheckpoint: FAIL
unexpected test termination
test/testfailures.cpp(68): last checkpoint: UP_ASSERT_EXCEPTION
suiteCheckpoints::AssertExceptionIsCheckpoint: FAIL
unexpected test termination
test/testfailures.cpp(74): last checkpoint: UP_ASSERT_EXCEPTION
suiteCheckpoints::AssertExceptionMessageIsCheckpoint: FAIL
unexpected test termination
test/testfailures.cpp(50): last checkpoint: UP_ASSERT
suiteCheckpoints::AssertIsCheckpoint: FAIL
unexpected test termination
test/testfailures.cpp(62): last checkpoint: UP_ASSERT_NE
suiteCheckpoints::AssertNeIsCheckpoint: FAIL
unexpected test termination
test/testfailures.cpp(86): last checkpoint: UP_ASSERT
suiteCheckpoints::CheckpointShoildBeFixedBeforeArgumentsEvaluate: FAIL
unexpected test termination: Signal (Floating point exception) received
test/testfailures.cpp(26): last checkpoint: run test
suiteCheckpoints::DivizionByZeroInTestShouldCheckpointed: FAIL
unexpected test termination: setUp exception for checkpoint
test/testfailures.cpp(18): last checkpoint: fixture setUp
suiteCheckpoints::ExceptionInFixtureShouldCheckpointed: FAIL
unexpected test termination
test/testfailures.cpp(91): last checkpoint: user checkpoint
suiteCheckpoints::ExplicitCheckpointShouldBe: FAIL
unexpected test termination: Signal (Segmentation fault) received
test/testfailures.cpp(39): last checkpoint: run test
suiteCheckpoints::SegFaultInTestShouldCheckpointed: FAIL
unexpected test termination
test/testfailures.cpp(7): last checkpoint: run test
suiteCheckpoints::UnhandledExceptionInTestShouldCheckpointed: FAIL
